### PR TITLE
More Widget colors

### PR DESCRIPTION
**Pull request by ALIRAQI**
Added Material Colors to Widget colors

### CODE REVIEW

**Comment by romannurik** [comment]
The issue with doing this is that analog clocks can't be colored :-/ We'd have to either disable the analog clocks or add additional logic.

**Comment by ALIRAQI** [comment]
i just noticed that 😅
so i need to make drawables for all colors like black & white version, then you have link it to the colors?

**Comment by ALIRAQI** [comment]
i checked analog clock files and i found it in 
    static String[] TIME_STYLE_NAMES = new String[]

i need to add new analog and adding layout xml for every color ?

**Comment by romannurik** [comment]
Unfortunately won't be pursuing this in the main DashClock app, sorry!

**Pull request closed without merging**
